### ISSUE TITLE
use python flask NOW organize your code and data better NOW `git clone` a life NOW

### ISSUE THREAD

**Issue by TechDudie** [OnlyGit-Official/OnlyGit#4]
use python flask NOW organize your code and data better NOW `git clone` a life NOW

**Comment by TechDudie** [comment]
ill see if i can format and spellcheck your dumb html for you

**Comment by Hardwaregore** [comment]
????? My main repo is on Bitbucket 😂😂😂🧐🧐🧐🤨🤨🤨🤔🤔🤔https://bitbucket.org/OnlyGit/OnlyGit

**Comment by Hardwaregore** [comment]
@TechDudie
