### ISSUE TITLE
terms of service and privacy policy

### ISSUE THREAD

**Issue by TechDudie** [OnlyGit-Official/OnlyGit#5]
yeah this definitely violates COPPA

**Comment by Hardwaregore** [comment]
wtf is coppa

**Comment by Hardwaregore** [comment]
Children's Online Privacy Protection Act??? 🤣

**Comment by Hardwaregore** [comment]
onlygit is   ✨under development✨

**Comment by Hardwaregore** [comment]
also, if I get sued, Lakewood middle school is liable because I was given 'consent' to build this application by Kate Peppe - the Guided Discovery teacher

**Comment by Hardwaregore** [comment]
The app will go through 2 rounds of testing:
1. The kids in my GD class
2. All LKMS 8th grade gifted kids in Ms. Pepper's flex class
All kids will be given ✨consent✨

**Comment by Hardwaregore** [comment]
also, I can see who visited the site via a thing called  ✨logs✨  and the  ✨admin panel✨

**Comment by Hardwaregore** [comment]
so anyone I don't recognize before it is released (with a tos) will be ✨terminated immediately✨

**Comment by Hardwaregore** [comment]
so shut up, idgaf about COPPA

**Comment by TechDudie** [comment]
at least add a terms of service and a privacy policy

**Comment by TechDudie** [comment]
bruh

**Comment by TechDudie** [comment]
```
Privacy Policy:

We steal and sell all your data.
```

**Comment by TechDudie** [comment]
just put that in privacy.php and you're all done its litearlly so easy

**Comment by Hardwaregore** [comment]
It's ✨under development✨

**Comment by Hardwaregore** [comment]
> ```
> Privacy Policy:
> 
> We steal and sell all your data.
> ```

this is illegal too btw.......................................................
